version: '3.4'

services:
  web_api:
    image: km-new-dockerfile
    container_name: web_api_application
    ports:
      - "5000:80"  
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql;Database=KitchenManager;User Id=sa;Password=Mypassword123!;TrustServerCertificate=True
    depends_on:
    - sql

  sql:
      image: "mcr.microsoft.com/mssql/server:2019-latest"
      container_name: sql
      ports:
        - "1433:1433"
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Mypassword123!
      
